######################################################################
# Automatically generated by qmake (2.01a) Fr 29. Feb 13:30:54 2008
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += glwidget.h window.h logwindow.h qtglut.h
SOURCES += glwidget.cpp main.cpp window.cpp logwindow.cpp qtglut.cpp
RC_FILE = qtgears.rc
